apiVersion: v1
kind: Service
metadata:
  name: permission
  namespace: web-app-k8s
  labels:
    app: permission
spec:
  selector:
    app: permission
  ports:
    - protocol: TCP
      port: 8005
      targetPort: 8005
  type: ClusterIP
