apiVersion: v1
kind: Secret

metadata:
  name: app-secret

type: Opaque

stringData:

  #MONGO_USER: "u1"
  #MONGO_PASSWORD: "somepw"
  #MONGO_DSN: "mongodb://u1:somepw@db:27017/testdb"

  MONGO_INITDB_ROOT_USERNAME: "admin"
  MONGO_INITDB_ROOT_PASSWORD: "admin"
  MONGO_DSN: "mongodb://admin:admin@mongo-service:27017/testdb?authSource=admin"

  JWT_SECRET: "CFjW7xv8lwSM4raGqFAL0Cqno9B8RXSol3rwm4lxr+c="

  MAILER_DSN: "smtps://kapilprajapat0011@gmail.com:tfjmpbexagyejjbt@smtp.gmail.com:465"
  MAILER_FROM: '"Microservice APP" <kapilprajapat0011@gmail.com>'