apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: web-app-k8s
spec:
  clusterIP: None
  #type: ClusterIP
  selector:
    app: Database-Mongodb-label
  ports:
  - port: 27017
    targetPort: 27017
