apiVersion: v1
kind: Secret

metadata:
  name: mongo-secret
  namespace: web-app-k8s

type: Opaque

stringData:

  #MONGO_USER: "u1"
  #MONGO_PASSWORD: "some"
  #MONGO_DSN: "mongodb://u1:some@db:27017/testdb"

  MONGO_INITDB_ROOT_USERNAME: "admin"
  MONGO_INITDB_ROOT_PASSWORD: "admin"
  MONGO_DSN: "mongodb://admin:admin@mongo-service:27017/testdb?authSource=admin"