apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: mystatefulset-mongodb
  namespace: web-app-k8s

spec:                                   # 1. STATEFULSET SPEC (Defines controllers/replicas)
  
  selector:
    matchLabels:
      app: Database-Mongodb-label       #A StatefulSet uses a selector to know which Pods belong to it.
  
  serviceName: mongo-service            #It must match the name of the headless service that you created for the StatefulSet.
  
  replicas: 1
  
  template:                             # 2. POD TEMPLATE
    metadata:
      labels:
        app: Database-Mongodb-label     #It is important to note that the labels of the Pod template must match the selector of the StatefulSet.
  
    spec: 
      nodeSelector:                     # 3. POD SPEC (Containers, ports, and mounts)
        #kubernetes.io/hostname: Clustername
        role: database
      
      containers:
      - name: database-mongodb 
        image: mongo:7.0.1
        #imagePullPolicy: IfNotPresent        # use only if the image is not present on the node, otherwise use the local image.


        livenessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 30 #Wait 30 seconds after startup.
          periodSeconds: 10       #Check every 10 seconds.
          timeoutSeconds: 5       #Each check can take up to 5 seconds.
          failureThreshold: 3     #Restart after 3 consecutive failures.

        readinessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3

        startupProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3

        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
            ephemeral-storage: "1Gi"
          limits:
            memory: "512Mi"
            cpu: "500m"
            ephemeral-storage: "1Gi"
        
        ports:
        - containerPort: 27017
          name: mongodb
        
        volumeMounts:
        - name: mypvc-inside-statefulset
          mountPath: /data/db
  
        envFrom:
        - secretRef:
            name: mongo-secret

        env:
        - name: MONGO_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mongodb-config
              key: MONGO_DATABASE

      #volumes:
      #- name: mypvc-for-mongodb
      #  persistentVolumeClaim:        
          #claimName: mypvc-for-mongodb #It must match the name of the PersistentVolumeClaim that you created for the StatefulSet.
  
  volumeClaimTemplates:
  - metadata:
      name: mypvc-inside-statefulset
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi