apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- api-gateway-deployment.yaml
- api-gateway-service.yaml
- mailer-deployment.yaml
- mailer-service.yaml
- permission-deployment.yaml
- permission-service.yaml
- task-deployment.yaml
- task-service.yaml
- token-deployment.yaml
- token-service.yaml
- user-deployment.yaml
- user-service.yaml
- config.yaml
- namespace.yaml
- secret.yaml
- database/mongo-config.yaml
- database/mongo-secret.yaml
- database/mongo-service.yaml
- database/mongodb-statefulset.yaml

images:
- name: kapilgole1/gateway
  newName: kapilgole1/gateway
  newTag: bfa40c7f389cd7fdf954d9f400e4a54a0326805b
- name: kapilgole1/mailer
  newName: kapilgole1/mailer
  newTag: bfa40c7f389cd7fdf954d9f400e4a54a0326805b
- name: kapilgole1/permission
  newName: kapilgole1/permission
  newTag: bfa40c7f389cd7fdf954d9f400e4a54a0326805b
- name: kapilgole1/task
  newName: kapilgole1/task
  newTag: bfa40c7f389cd7fdf954d9f400e4a54a0326805b
- name: kapilgole1/token
  newName: kapilgole1/token
  newTag: bfa40c7f389cd7fdf954d9f400e4a54a0326805b
- name: kapilgole1/user
  newName: kapilgole1/user
  newTag: bfa40c7f389cd7fdf954d9f400e4a54a0326805b
