apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - api-gateway-deployment.yaml
  - api-gateway-service.yaml
  - mailer-deployment.yaml
  - mailer-service.yaml
  - permission-deployment.yaml
  - permission-service.yaml
  - task-deployment.yaml
  - task-service.yaml
  - token-deployment.yaml
  - token-service.yaml
  - user-deployment.yaml
  - user-service.yaml
  - config.yaml
  - namespace.yaml
  - secret.yaml
  - database/mongo-config.yaml
  - database/mongo-secret.yaml
  - database/mongo-service.yaml
  - database/mongodb-statefulset.yaml

images:
  - name: <DOCKERHUB_ORG>/gateway
    newTag: latest
  - name: <DOCKERHUB_ORG>/mailer
    newTag: latest
  - name: <DOCKERHUB_ORG>/permission
    newTag: latest
  - name: <DOCKERHUB_ORG>/task
    newTag: latest
  - name: <DOCKERHUB_ORG>/token
    newTag: latest
  - name: <DOCKERHUB_ORG>/user
    newTag: latest