apiVersion: v1
kind: Secret

metadata:
  name: app-secret
  namespace: web-app-k8s

type: Opaque

stringData:

  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  MONGO_INITDB_ROOT_USERNAME: ${{ secrets.MONGO_INITDB_ROOT_USERNAME }}
  MONGO_INITDB_ROOT_PASSWORD: ${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}
  MONGO_DSN: ${{ secrets.MONGO_DSN }}

  MAILER_DSN: ${{ secrets.MAILER_DSN }}
  MAILER_FROM: ${{ secrets.MAILER_FROM }}