apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-deployment
  namespace: web-app-k8s
  labels:
    app: task
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task
  template:
    metadata:
      labels:
        app: task
    spec:
      containers:
        - name: task
          image: kapilgole1/task:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8001
          env:
            - name: TASK_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: TASK_SERVICE_PORT
            - name: MONGO_DSN
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_DSN
